### ISSUE TITLE
[BUG] On resize Header and body of the tables are mismatched

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#318]
When you resize the window table's header and columns are resized differently

<img width="850" alt="Screen Shot 2022-03-09 at 5 55 10 PM" src="https://user-images.githubusercontent.com/55718143/157573273-b50dc80b-44b9-461d-9f26-14ca33a92b1f.png">

#### Can be seen in next views
Workflow execution view:
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/workflows/athena.athena.no_io_wf?duration=all

Nodes view:
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/gcg0wvmhfh?duration=all

Task execution view:
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/tasks/athena.athena.print_athena_schema?duration=all

Executions view:
https://demo.nuclyde.io/console/projects/flytesnacks/executions?duration=all

**Comment by eugenejahn** [comment]
when resizing windows to smaller heights, the rows will disappear. The row disappears because the components above already take all the windows height, so the table rows container height set to 0px. 
 
![image](https://user-images.githubusercontent.com/25038146/162598529-699a73a0-7bdf-4a44-b10f-7e1b7e79d64f.png)


![image](https://user-images.githubusercontent.com/25038146/162598533-02c14dec-79ad-4e14-9c29-d261fadaf717.png)
