### ISSUE TITLE
[BUG] Dimensionality - should be set per data type blob and be disabled in UI.

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#336]
### Issue:
FlyteUI dimensionality defaults to Single when the input type is a FlyteDirectory .

### Repro:
Open folder task in DEMO site: 
 - https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/tasks/core.basic.folders.rotate_all?duration=all
- Click "Launch Task" button
- Observe that `img_dir (file/blob)*` expects to get directory as an input, but dimensionality is set to "Single (File)"

[Task template](https://demo.nuclyde.io/api/v1/tasks/flytesnacks/development/core.basic.folders.rotate_all/773447b298bfa8ecfc2b25983ce1ed2d33753d01) sets dimensionality for this data to MULTIPART 
```
"img_dir": {
  "type": {
     "blob": {
        "dimensionality": "MULTIPART"
      }
    },
  "description": "img_dir"
}
``` 

### How should fix look like

Dimensionality should match data contract specified in data type. Control should be disabled, so the user can see type but won't be able to switch it.

### Notify on thread fix:
https://flyte-org.slack.com/archives/CREL4QVAQ/p1646872001275689

**Comment by eugenejahn** [comment]
hi! 
I was trying to solve this issue, can produce it, and have looked into the codebase, but not pretty sure what is the expected behavior. 

It looks like we already matching the dimensionality from the data contract, and if empty, the default dimensionality is set to 0 
https://github.com/flyteorg/flyteconsole/blob/4721e84e43dee81b52f1e89cc1e555529717cb15/src/components/Launch/LaunchForm/BlobInput.tsx#L41

so the only issue I see is that we didn't disable the drop-down. Then we should set the select componet to disabled,  so the user can see type but won't be able to switch it.
https://github.com/flyteorg/flyteconsole/blob/4721e84e43dee81b52f1e89cc1e555529717cb15/src/components/Launch/LaunchForm/BlobInput.tsx#L100-L109


Let me know if that's correct! Thanks. Also, if you want, you can also slack me for communication:)

**Comment by anrusina** [comment]
To get to BlobInput we are first checking `input.typeDefinition.type` in https://github.com/flyteorg/flyteconsole/blob/4721e84e43dee81b52f1e89cc1e555529717cb15/src/components/Launch/LaunchForm/LaunchFormInputs.tsx#L19

So get proper dimensionality we need to use `props.typeDefinition.literalType.blob.dimensionality` value in https://github.com/flyteorg/flyteconsole/blob/4721e84e43dee81b52f1e89cc1e555529717cb15/src/components/Launch/LaunchForm/BlobInput.tsx#L41

Looks like `defaultBlobValue` was only used in this file so we can safe replace it with something like:
```
const dimensionality = props?.typeDefinition?.literalType?.blob?.dimensionality;
const blobValue = isBlobValue(propValue) ? propValue : {
  uri: '',
  dimensionality: dimensionality ?? BlobDimensionality.SINGLE,
}
```
+ As you mentioned - disable `Select`
