### ISSUE TITLE
Bug: Dynamic tasks not showing in Execution View

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#512]
A user on the open slack channel has noted that they cannot see their dynamic (sub) tasks. This ticket will track investigating and fixing this issue.

From user: "hi flyte team, we recently upgraded the console to the latest and now it doesn't show dynamic subtasks"
```
  flyteadmin_version     = "v1.1.21"
  flyteconsole_version   = "v1.1.0"
  flytecopilot_version   = "v0.0.26"
  flytepropeller_version = "v1.1.12"
  ```
  ![Screen Shot 2022-06-16 at 2 39 24 PM (1)](https://user-images.githubusercontent.com/84735036/174170902-3e3325fa-ec99-4f3a-aa62-d623fb6448ec.png)

**Comment by eugenejahn** [comment]
Hey Jason. I am not pretty sure what is the expected behavior look like. is that supposed to like the screenshot below?  also, the screenshot 

From the demo link: Success 
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/fca7f4c94fca745f88d8?duration=all
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/25038146/174342186-1802d79b-ffe8-4bbb-93e0-bf8b1879a665.png">

From the demo link: Failed
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/a67j46dcw4wnqmpqdhzt?duration=all
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/25038146/174343167-dd04bb93-0070-4cee-a19a-b9dd2414003f.png">


Slack discussions: https://flyte-org.slack.com/archives/CNMKCU6FR/p1655414807481039

**Comment by anrusina** [comment]
@Eugene - the tasks you are referring to in your comment is mapTasks [read: an array pf tasks which run the same task with different input parameters]
The Dynamic task is a task which execution depend on the input provided. In case with subworkflows , sample example would be that Dynamic task can call task A if input number > 5 and task B if input number < 5 and task C if input == 5.
The Docs: https://docs.flyte.org/projects/cookbook/en/stable/auto/core/control_flow/dynamics.html
Dynamic node samples in Demo I usually use:
https://demo.nuclyde.io/console/projects/[flytesnacks/domains/development/executions/](https://localhost.demo.nuclyde.io:3000/projects/flytesnacks/domains/development/executions/rnktdb3skr?duration=all)[mjnv9tfbd5?duration=all](https://localhost.demo.nuclyde.io:3000/projects/flytesnacks/domains/development/executions/mjnv9tfbd5?duration=all) 

[Dynamic + Branch] https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/zalmx8wnp3?duration=all

**Comment by anrusina** [comment]
WORKS:
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/ema7b7lpvl?duration=all
NOT WORKING:
https://demo.nuclyde.io/console/projects/flytesnacks/domains/development/executions/afm54zx92vt852shm4fk?duration=all

**Comment by anrusina** [comment]
Currently, looks like backend API issue
https://flyte-org.slack.com/archives/CNMKCU6FR/p1655414807481039
https://unionai.slack.com/archives/C01H0FN1NJX/p1655848341242169

**Comment by jsonporter** [comment]
Confirmed with BE; this is not a FE bug. Closing
