### ISSUE TITLE
[BUG] No Cache icon showing up for cached MapTasks

### ISSUE THREAD

**Issue by anrusina** [flyteorg/flyteconsole#514]
In flyteconsole 0.19.4 it does look like the map task is caching even though the little swirly isn't present in the ui
Issue is reproduced by @eugenejahn on flyteconsole 1.1.1

### Notify on completion:
https://flyte-org.slack.com/archives/CNMKCU6FR/p1655303400482879

**Comment by anrusina** [comment]
Eugene reproduced issue locally. Regular tasks locally had cache icon.
Code example used:

```
import typing
import pandas as pd
import numpy as np
from flytekit import Resources, map_task, task, workflow

@task
def coalesce(b: typing.List[str]) -> str:
    coalesced = "".join(b)
    return coalesced

@task(cache=True, cache_version="1.0")
def a_mappable_cache_task(a: int) -> str:
    inc = a + 2
    stringified = str(inc)
    return stringified

@task(cache=True, cache_serialize=True, cache_version="1.0")
def square(n: int) -> int:
    """
     Parameters:
        n (int): name of the parameter for the task will be derived from the name of the input variable.
                 The type will be automatically deduced to Types.Integer

    Return:
        int: The label for the output will be automatically assigned, and the type will be deduced from the annotation

    """
    return n * n

@workflow
def wf2(a: int) -> int:
    out = square(n=a)
    return out
```

**Comment by eugenejahn** [comment]
Just double-check with @hamersaw, for now, map tasks will require the task_executions endpoint to get cache information (along with phase, etc) and all other tasks should continue using the node_executions endpoint. In the future, we would certainly like the change this so that map task execution is exactly the same as regular tasks. So you could use the same API.

 Since our frontend use node_executions endpoint to check the cache status, we can't detect the cache status for maptaks, and that's why no cache icon show up. To fix this, we need to use the task_executions endpoint to check the cache status for map tasks.
